parameters:
    uncleempty_maintenance.listener.class: Uncleempty\MaintenanceBundle\EventListeners\MaintenanceEventListener
services:
#    uncleempty_maintenance.example:
#        class: Uncleempty\MaintenanceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    uncleempty_maintenance.listener:
        class: %uncleempty_maintenance.listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [@http_kernel, @request_stack]
