parameters:
    uncleempty_maintenance.listener.class: Uncleempty\MaintenanceBundle\EventListeners\MaintenanceEventListener
services:
    uncleempty_maintenance.listener:
        class: %uncleempty_maintenance.listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
