language: php

php:
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - hhvm


env:
  - SYMFONY_EXTRA_VERSION="~3.0,>=3.0.2"
#  - SYMFONY_VERSION="2.5.*"
#  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
#  - SYMFONY_VERSION="2.8.*"
#  - SYMFONY_VERSION="3.0.*"

before_script:
  - composer self-update
  - composer require --dev symfony/symfony=$SYMFONY_VERSION
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer require sensio/framework-extra-bundle:${SYMFONY_EXTRA_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - yarkovets.i@gmail.com
