language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm


env:
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

notifications:
  email:
    - yarkovets.i@gmail.com
