language: php

php:
  - 5.5
  - 5.6


env:
  - SYMFONY_VERSION="2.7.*"

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - yarkovets.i@gmail.com
